#!/usr/bin/env python3
"""Turn the hand-editable adult Totoro worksheet into the firmware sprite sheet.

Input is `assets/totoro_adult_worksheet.png`: clean pixel art at native
resolution, laid out on the fixed grid described below. Edit that PNG in any
pixel editor and rerun this script; nothing else needs to change.

    +-----------------------------------------------+
    | band 0: 7 pose cells, CELL_W x CELL_H         |
    +-----------------------------------------------+
    | band 1: 10 eye cells, EYE_W x EYE_H           |  5 pairs, then 5 singles
    +-----------------------------------------------+
    | band 2: 7 x 5 pose+eye reference (ignored)    |
    +-----------------------------------------------+

Cells are separated by a 1px gutter that this script never reads, so the
gutters are free to hold guide lines. Band 2 is a reference for the artist and
is regenerated by `generate_totoro_adult_worksheet.py --refresh`.

Bodies and faces stay separate cells so a new expression costs one small cell
instead of a whole extra set of poses. Two rules the runtime depends on:

* The reference shows a **single eye** on the side-facing poses, so the sheet
  carries both a pair and a single-eye cut of every expression and `EyeBase[]`
  says which set to hang on each pose.
* Bodies are centred on their own cell rather than on the eye, so mirroring a
  cell moves the eye socket. `EyeOffsetX[]` is therefore per pose and the
  runtime mirrors it as `cellW - eyeW - offsetX`.

    python3 tools/generate_totoro_adult_sheet.py
    python3 tools/generate_totoro_adult_sheet.py --scale 2 --colors 12
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("Pillow is required: pip install pillow", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, os.path.dirname(__file__))
from sprite_encoding import encode_sheet, preview_stats, write_asset_header  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKSHEET = os.path.join(ROOT, "assets", "totoro_adult_worksheet.png")
OUTPUT = os.path.join(ROOT, "src", "sprite_totoro_adult.h")
PREVIEW = os.path.join(ROOT, "assets", "sprite_totoro_adult_preview.png")
NAME = "sprite_totoro_adult"

# --- Worksheet grid (native pixels, before the chunky --scale upscale) -------
CELL_W = 46
CELL_H = 56
EYE_W = 26
EYE_H = 12
GUTTER = 1
POSE_COUNT = 7
EYE_VARIANTS = 5

# Band 0, left to right: 1 standing, 2 dancing / walking toward the viewer,
# 3 hungry (paws clutching the belly), 4 sitting front, 5-6 walking left,
# 7 sitting facing left.
POSE_CELLS = [1, 2, 3, 4, 5, 6, 7]

# Poses drawn side-on: these wear the single-eye cells.
SIDE_POSES = {5, 6, 7}

# Top-left of the eye cell within the pose cell, in native pixels. Derived once
# from the artist's 7x5 reference matrix in the original render (see
# `generate_totoro_adult_worksheet.py`); this table is now the source of truth.
# Nudge a pair of numbers here to move a face, or nudge the eyes inside their
# worksheet cell for sub-cell tweaks.
EYE_OFFSETS = {
    1: (9, 10),
    2: (9, 13),
    3: (9, 11),
    4: (9, 17),
    5: (1, 11),
    6: (0, 11),
    7: (1, 13),
}

# The region table the scene indexes into. Entries 0..5 keep the ordering the
# other sheets use (TOTORO_RGN_* in Scene_PetTotoro) so sheets stay
# interchangeable; the rest are specific to this art. Several regions
# deliberately alias the same cell.
BODY_REGIONS = [
    ("walk_a", 5),
    ("walk_b", 6),
    ("sit", 4),
    ("stand", 1),
    ("sleep", 4),
    ("blink", 1),
    ("hungry", 3),
    ("dance", 2),
    ("sit_side", 7),
]


def pose_cell_box(index):
    """Rect of pose cell `index` (0-based) in band 0."""
    x = index * (CELL_W + GUTTER)
    return (x, 0, x + CELL_W, CELL_H)


def eye_cell_box(index):
    """Rect of eye cell `index` (0-based, pairs then singles) in band 1."""
    x = index * (EYE_W + GUTTER)
    y = CELL_H + GUTTER
    return (x, y, x + EYE_W, y + EYE_H)


def matrix_cell_box(col, row):
    """Rect of the reference composite for pose `col`, eye `row` in band 2."""
    x = col * (CELL_W + GUTTER)
    y = CELL_H + GUTTER + EYE_H + GUTTER + row * (CELL_H + GUTTER)
    return (x, y, x + CELL_W, y + CELL_H)


def worksheet_size():
    right = matrix_cell_box(POSE_COUNT - 1, 0)[2]
    bottom = matrix_cell_box(0, EYE_VARIANTS - 1)[3]
    return right, bottom


def eye_cell_index(variant, side):
    """Band 1 cell holding `variant` (0-based), as a pair or a single eye."""
    return variant + (EYE_VARIANTS if side else 0)


def read_worksheet(path):
    """Slice the fixed grid out of the worksheet, ignoring gutters and band 2."""
    sheet = Image.open(path).convert("RGBA")
    need_w, need_h = worksheet_size()
    if sheet.width < need_w or sheet.height < need_h:
        raise SystemExit(
            f"{path} is {sheet.width}x{sheet.height}; the grid needs at least "
            f"{need_w}x{need_h}. Did the cell size change?"
        )
    bodies = {pose: sheet.crop(pose_cell_box(i)) for i, pose in enumerate(POSE_CELLS)}
    eyes = [sheet.crop(eye_cell_box(i)) for i in range(2 * EYE_VARIANTS)]
    return bodies, eyes


def flatten_palette(sheet, colors):
    """Median-cut the opaque pixels if hand edits blew the palette budget."""
    rgb = sheet.convert("RGB")
    alpha = sheet.getchannel("A")
    opaque = [rgb.getpixel((x, y))
              for y in range(sheet.height) for x in range(sheet.width)
              if alpha.getpixel((x, y))]
    if len(set(opaque)) <= colors:
        return sheet
    sample = Image.new("RGB", (len(opaque), 1))
    sample.putdata(opaque)
    palette = sample.quantize(colors=colors, method=Image.MEDIANCUT, dither=Image.NONE)
    out = rgb.quantize(palette=palette, dither=Image.NONE).convert("RGBA")
    out.putalpha(alpha)
    return out


def build_sheet(bodies, eyes, scale):
    cell_w, cell_h = CELL_W * scale, CELL_H * scale
    eye_w, eye_h = EYE_W * scale, EYE_H * scale

    def upscale(img):
        if scale == 1:
            return img
        return img.resize((img.width * scale, img.height * scale), Image.NEAREST)

    sheet_w = max(cell_w * POSE_COUNT, eye_w * len(eyes))
    sheet = Image.new("RGBA", (sheet_w, cell_h + eye_h), (0, 0, 0, 0))
    for i, pose in enumerate(POSE_CELLS):
        sheet.alpha_composite(upscale(bodies[pose]), (i * cell_w, 0))
    for i, eye in enumerate(eyes):
        sheet.alpha_composite(upscale(eye), (i * eye_w, cell_h))

    regions = [(label, POSE_CELLS.index(pose) * cell_w, 0, cell_w, cell_h)
               for label, pose in BODY_REGIONS]
    regions += [(f"eye{i % EYE_VARIANTS + 1}" + ("_side" if i >= EYE_VARIANTS else ""),
                 i * eye_w, cell_h, eye_w, eye_h)
                for i in range(len(eyes))]

    body_count = len(BODY_REGIONS)
    pair_base = body_count
    single_base = body_count + EYE_VARIANTS
    meta = {
        "cell_w": cell_w,
        "cell_h": cell_h,
        "eye_w": eye_w,
        "eye_h": eye_h,
        "eye_base": [single_base if pose in SIDE_POSES else pair_base
                     for _label, pose in BODY_REGIONS],
        "eye_offset_x": [EYE_OFFSETS[pose][0] * scale for _label, pose in BODY_REGIONS],
        "eye_offset_y": [EYE_OFFSETS[pose][1] * scale for _label, pose in BODY_REGIONS],
        "pair_base": pair_base,
        "single_base": single_base,
        "variants": EYE_VARIANTS,
    }
    for pose, (ox, oy) in EYE_OFFSETS.items():
        if not (0 <= ox <= CELL_W - EYE_W and 0 <= oy <= CELL_H - EYE_H):
            raise SystemExit(f"EYE_OFFSETS[{pose}] = ({ox}, {oy}) puts the eye outside the cell")
    return sheet, regions, meta


def append_metadata(path, name, meta, body_count):
    """Bolt the attach-offset tables onto the shared asset header."""
    upper = name.upper()

    def table(values):
        return ", ".join(str(v) for v in values)

    extra = f"""
// --- Runtime face compositing -------------------------------------------
// The first {body_count} regions are bodies; the rest are eye strips: {meta['variants']} pairs
// followed by {meta['variants']} single eyes for the side-facing poses.
// Hang region ({name}EyeBase[body] + variant) on the body at
// ({name}EyeOffsetX[body], {name}EyeOffsetY[body]).
#define {upper}_BODY_REGION_COUNT {body_count}
#define {upper}_EYE_REGION {meta['pair_base']}
#define {upper}_EYE_SIDE_REGION {meta['single_base']}
#define {upper}_EYE_VARIANTS {meta['variants']}

static const uint8_t {name}EyeBase[{body_count}] PROGMEM = {{
  {table(meta['eye_base'])}
}};

// Bodies are centred on their own cell, not on the eye, so a mirrored cell
// moves the socket: the runtime uses (cellW - eyeW - offsetX) when flipped.
static const uint8_t {name}EyeOffsetX[{body_count}] PROGMEM = {{
  {table(meta['eye_offset_x'])}
}};

static const uint8_t {name}EyeOffsetY[{body_count}] PROGMEM = {{
  {table(meta['eye_offset_y'])}
}};
"""
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    head, sep, tail = text.rpartition("#endif")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(head + extra + "\n" + sep + tail)


def compose(bodies, eyes, pose, variant, scale=1):
    """Runtime compositing, for previews: one body wearing one expression."""
    cell = bodies[pose].copy()
    eye = eyes[eye_cell_index(variant, pose in SIDE_POSES)]
    cell.alpha_composite(eye, EYE_OFFSETS[pose])
    if scale != 1:
        cell = cell.resize((cell.width * scale, cell.height * scale), Image.NEAREST)
    return cell


def save_preview(path, bodies, eyes, scale):
    """Draw the runtime composite: every body wearing every face."""
    cell_w, cell_h = CELL_W * scale, CELL_H * scale
    out = Image.new("RGBA", (cell_w * len(BODY_REGIONS), cell_h * EYE_VARIANTS),
                    (86, 132, 86, 255))
    for variant in range(EYE_VARIANTS):
        for col, (_label, pose) in enumerate(BODY_REGIONS):
            out.alpha_composite(compose(bodies, eyes, pose, variant, scale),
                                (col * cell_w, variant * cell_h))
    out.convert("RGB").save(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-i", "--worksheet", default=WORKSHEET)
    parser.add_argument("--scale", type=int, default=2,
                        help="Nearest-neighbour upscale from worksheet to screen pixels")
    parser.add_argument("--colors", type=int, default=16,
                        help="Palette ceiling; hand edits above it get median-cut")
    parser.add_argument("--bpp", type=int, default=4, choices=[4, 8, 16])
    parser.add_argument("-o", "--output", default=OUTPUT)
    parser.add_argument("-n", "--name", default=NAME)
    parser.add_argument("--preview-out", default=PREVIEW)
    args = parser.parse_args()

    if args.bpp == 4 and args.colors > 16:
        raise SystemExit("4-bpp sprites hold at most 16 palette entries")

    bodies, eyes = read_worksheet(args.worksheet)
    sheet, regions, meta = build_sheet(bodies, eyes, args.scale)
    sheet = flatten_palette(sheet, args.colors)
    if sheet.width % 2:
        raise SystemExit("Sheet width must be even: 4-bpp rows are one nibble stream")

    encoded = encode_sheet(sheet, regions, args.bpp, None)
    write_asset_header(args.output, args.name, encoded)
    body_count = len(BODY_REGIONS)
    append_metadata(args.output, args.name, meta, body_count)

    print(f"Wrote {args.output}")
    print(f"  {POSE_COUNT} body cells + {2 * EYE_VARIANTS} eye cells, "
          f"{len(regions)} regions, cell {meta['cell_w']}x{meta['cell_h']}, "
          f"eye {meta['eye_w']}x{meta['eye_h']}")
    print(preview_stats(encoded))
    if args.preview_out:
        save_preview(args.preview_out, bodies, eyes, args.scale)
        print(f"Preview PNG: {args.preview_out}")


if __name__ == "__main__":
    main()
