#!/usr/bin/env python3
"""Emit the trained gesture model as a C header the firmware compiles in.

Only the flatbuffer, no scaler: GestureFeatures.h normalises every feature by
construction, so unlike the care-action model there are no fitted constants that
have to be shipped alongside and kept in step.

The one thing that can silently break is the feature count. The header the device
builds its input from and the model's input tensor have to agree, and they are
edited in different places by different people. So this reads the extractor's own
defines and refuses to write a header that disagrees with the model.

Usage:
  python export_gesture_header.py
  python export_gesture_header.py --model models/gesture.tflite
"""

from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

import tensorflow as tf

from train_gesture import LABELS

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "src"
FEATURES_HEADER = SRC / "ml" / "GestureFeatures.h"
DEFAULT_OUT = SRC / "ml" / "models" / "gesture_model.h"


def extractor_feature_count() -> tuple[int, int, int]:
    """Read GESTURE_RESAMPLE_POINTS and GESTURE_SCALAR_FEATURES from the C header."""
    text = FEATURES_HEADER.read_text()

    def define(name: str) -> int:
        match = re.search(rf"^#define\s+{name}\s+(\d+)", text, re.MULTILINE)
        if not match:
            raise SystemExit(f"cannot find {name} in {FEATURES_HEADER}")
        return int(match.group(1))

    points = define("GESTURE_RESAMPLE_POINTS")
    scalars = define("GESTURE_SCALAR_FEATURES")
    return points, scalars, points * 2 + scalars


def model_shapes(path: Path) -> tuple[int, int]:
    interpreter = tf.lite.Interpreter(model_path=str(path))
    interpreter.allocate_tensors()
    input_shape = interpreter.get_input_details()[0]["shape"]
    output_shape = interpreter.get_output_details()[0]["shape"]
    return int(input_shape[-1]), int(output_shape[-1])


def reject_quantized_weights(path: Path) -> None:
    """Refuse a hybrid model, which this TFLite Micro build silently computes as NaN.

    tf.lite.Optimize.DEFAULT quantizes weight tensors over a size threshold and
    leaves smaller ones alone, so a model can come out part int8 and part float32.
    That needs the int8-weight, float-activation FullyConnected kernel, which the
    TensorFlowLite_ESP32 snapshot does not implement - and it fails by returning
    NaN rather than by refusing to run. Cheaper to catch here than on hardware.
    """
    interpreter = tf.lite.Interpreter(model_path=str(path))
    interpreter.allocate_tensors()

    offenders = []
    for detail in interpreter.get_tensor_details():
        dtype = detail["dtype"].__name__
        if detail["shape"].size and dtype not in ("float32", "int32"):
            offenders.append(f"{detail['name'] or '?'} ({dtype})")

    if offenders:
        raise SystemExit(
            f"{path.name} contains non-float weights: {', '.join(offenders)}.\n"
            "TFLite Micro here cannot run hybrid models and returns NaN for them. "
            "Remove converter.optimizations from train_gesture.py and retrain, or "
            "quantize fully with a representative dataset."
        )


def format_bytes(blob: bytes, per_line: int = 12) -> str:
    lines = []
    for start in range(0, len(blob), per_line):
        chunk = blob[start : start + per_line]
        lines.append("  " + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=HERE / "models" / "gesture.tflite")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    if not args.model.exists():
        raise SystemExit(f"missing {args.model}; run train_gesture.py first")

    reject_quantized_weights(args.model)

    points, scalars, expected_features = extractor_feature_count()
    model_features, model_labels = model_shapes(args.model)

    if model_features != expected_features:
        raise SystemExit(
            f"the model takes {model_features} features but "
            f"{FEATURES_HEADER.name} builds {expected_features} "
            f"({points} resampled points x2 + {scalars} scalars).\n"
            "Re-run prepare_gestures.py and train_gesture.py after changing the "
            "extractor, so the model is trained on the features the device sends."
        )
    if model_labels != len(LABELS):
        raise SystemExit(
            f"the model has {model_labels} outputs but {len(LABELS)} labels are defined"
        )

    blob = args.model.read_bytes()

    header = f"""#ifndef _GESTURE_MODEL_H_
#define _GESTURE_MODEL_H_

// Generated by tinyml/export_gesture_header.py on {date.today().isoformat()} - do not edit.
// Source: {args.model.name} ({len(blob)} bytes)
//
// Include from exactly one translation unit (GesturePredictor.cpp); the array is
// static, so a second include would duplicate it in flash.
//
// Not PROGMEM: the ESP32 maps flash into the address space, so TFLite Micro reads
// the flatbuffer in place. The 16-byte alignment is what it does require.
//
// Input is whatever gestureExtractFeatures() writes, in that order - the export
// refuses to run if the count here and in GestureFeatures.h disagree.
// Output order matches the GestureLabel enum:
//   {", ".join(LABELS)}

#define GESTURE_MODEL_FEATURE_COUNT {model_features}
#define GESTURE_MODEL_LABEL_COUNT {model_labels}
#define GESTURE_MODEL_TFLITE_LEN {len(blob)}

alignas(16) static const unsigned char gesture_model_tflite[GESTURE_MODEL_TFLITE_LEN] = {{
{format_bytes(blob)}
}};

#endif
"""

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header)
    print(
        f"wrote {args.output.relative_to(SRC.parent)} "
        f"({len(blob)} bytes of model, {model_features} features, {model_labels} labels)"
    )


if __name__ == "__main__":
    main()
