#!/usr/bin/env python3
"""Emit the trained care-action model as a C header the firmware compiles in.

The header carries the TFLite flatbuffer *and* the StandardScaler constants from
training. Both are required: the network was fitted on standardized features, so
on-device inference has to apply (x - mean) / scale in the same feature order or
the outputs are meaningless.

Usage:
  python export_model_header.py
  python export_model_header.py --model models/care_action.tflite -o ../src/ml/models/care_action_model.h
"""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

import numpy as np

from prepare_dataset import FEATURES, LABELS

HERE = Path(__file__).resolve().parent
DEFAULT_OUT = HERE.parent / "src" / "ml" / "models" / "care_action_model.h"


def format_bytes(blob: bytes, per_line: int = 12) -> str:
    lines = []
    for start in range(0, len(blob), per_line):
        chunk = blob[start : start + per_line]
        lines.append("  " + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def format_floats(values: np.ndarray) -> str:
    return ",\n".join(f"  {v:.8f}f" for v in values)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=HERE / "models" / "care_action.tflite")
    parser.add_argument("--mean", type=Path, default=HERE / "models" / "scaler_mean.npy")
    parser.add_argument("--scale", type=Path, default=HERE / "models" / "scaler_scale.npy")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    for path in (args.model, args.mean, args.scale):
        if not path.exists():
            raise SystemExit(f"Missing {path}. Run train_care_action.py first.")

    blob = args.model.read_bytes()
    mean = np.load(args.mean).astype(np.float32)
    scale = np.load(args.scale).astype(np.float32)

    if len(mean) != len(FEATURES) or len(scale) != len(FEATURES):
        raise SystemExit(
            f"Scaler has {len(mean)} entries but FEATURES has {len(FEATURES)}; retrain."
        )
    # A zero scale would divide by zero on-device; StandardScaler emits 1.0 for
    # constant columns, but a hand-edited dataset can still produce one.
    if (scale == 0).any():
        raise SystemExit("Scaler scale contains 0; a feature column is constant.")

    header = f"""#ifndef _CARE_ACTION_MODEL_H_
#define _CARE_ACTION_MODEL_H_

// Generated by tinyml/export_model_header.py on {date.today().isoformat()} — do not edit.
// Source: {args.model.name} ({len(blob)} bytes)
//
// Include from exactly one translation unit (CareActionPredictor.cpp); the
// arrays are static, so a second include would duplicate them in flash.
//
// Not PROGMEM: the ESP32 maps flash into the address space, so TFLite Micro can
// read the flatbuffer in place. The 16-byte alignment is what it does require.
//
// Feature order must match GameplaySample field order exactly:
//   {", ".join(FEATURES)}
// Output order:
//   {", ".join(LABELS)}

#define CARE_MODEL_FEATURE_COUNT {len(FEATURES)}
#define CARE_MODEL_LABEL_COUNT {len(LABELS)}
#define CARE_MODEL_TFLITE_LEN {len(blob)}

alignas(16) static const unsigned char care_action_model_tflite[CARE_MODEL_TFLITE_LEN] = {{
{format_bytes(blob)}
}};

// The model was trained on standardized inputs: feed it (x - mean) / scale.
static const float care_action_scaler_mean[CARE_MODEL_FEATURE_COUNT] = {{
{format_floats(mean)}
}};

static const float care_action_scaler_scale[CARE_MODEL_FEATURE_COUNT] = {{
{format_floats(scale)}
}};

#endif
"""

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header)
    print(f"Wrote {args.output} ({len(header)} chars, model {len(blob)} bytes)")


if __name__ == "__main__":
    main()
