#ifndef _SCENE_CATBUSCROSS_H_
#define _SCENE_CATBUSCROSS_H_

#include <Arduino.h>
#include "GameScene.h"
#include "GameSceneIds.h"
#include "GameResult.h"
#include "Input.h"
#include "ml/MLGameHooks.h"
#include "SpriteSheet.h"
#include "SpriteText.h"
#include "TouchInput.h"
#include "image_catbus_cross_bg.h"
#include "sprite_catbus_soot.h"
#include "sprite_digits.h"
#include "sprite_mei.h"

// Mei crosses five soot-patrolled lanes to reach the Goal sign at the top.
//
// The board - forest, Goal sign, lanes, start strip, side scenery and the two
// HUD plates - is one background image generated by tools/generate_catbus_bg.py
// from the concept art. Only Mei, the soot and the score digits are Avatars, so
// renderScene()'s dirty rectangles stay small.
//
// Movement is Frogger-style: Left/Right walk within the current lane, Home (or
// a tap on the upper half) hops up one lane. There is exactly one soot per lane
// and it is 22px wide in a 188px lane, so a lane is passable ~88% of the time;
// the challenge is timing the hop, never a wall with no gap in it.

#define CBC_LANE_COUNT 5
#define CBC_SOOT_W 22
#define CBC_SOOT_H 21
#define CBC_MEI_W 24
#define CBC_MEI_H 34

// Playfield geometry, in screen pixels, measured off the background art.
// Lanes run bottom-up: index 0 is the first one Mei steps into.
#define CBC_FIELD_X0 24
#define CBC_FIELD_X1 211
#define CBC_START_BOTTOM 255
#define CBC_GOAL_Y 44

// How far past the dirt a soot travels before wrapping, so it walks in and out
// of the foliage at the edges instead of popping in mid-lane. Sized so that at
// either extreme it is clear of the dirt but still inside the framed area.
#define CBC_SOOT_MARGIN 18

// Rows: 0 = start strip, 1..CBC_LANE_COUNT = lanes, then the goal.
#define CBC_GOAL_ROW (CBC_LANE_COUNT + 1)

#define CBC_PLAYER_SPEED 3.6f
#define CBC_MEI_FRAME_MS 90
#define CBC_HOP_COOLDOWN_MS 200
#define CBC_INTRO_GRACE_MS 350
#define CBC_HIT_HOLD_MS 700
#define CBC_START_ATTEMPTS 3
// Win when Mei reaches the goal within this many milliseconds.
#define CBC_WIN_TIME_MS 8000
// Collision inset: a graze that only clips the outline should not count.
#define CBC_HIT_INSET 3

#define CBC_SCORE_X 31
#define CBC_SCORE_Y 11
#define CBC_SCORE_DIGIT_W 10
#define CBC_SCORE_GAP 2
#define CBC_BANNER_POOL 8
#define CBC_BANNER_Y 150
// "Tap to replay" pill, sat just under the banner glyphs (which are 20px tall).
#define CBC_HINT_Y 174
#define CBC_HINT_H 22

static const int16_t CBC_LANE_TOP[CBC_LANE_COUNT] = {190, 160, 132, 103, 75};
static const int16_t CBC_LANE_BOTTOM[CBC_LANE_COUNT] = {218, 186, 156, 128, 100};

enum CatBusCrossState {
  CBC_STATE_READY,
  CBC_STATE_PLAYING,
  CBC_STATE_HIT,
  CBC_STATE_WON,
  CBC_STATE_LOST
};

class Scene_CatBusCross : public GameScene {
  public:
    Scene_CatBusCross(TFT_eSPI *tft) {
      GameScene::_tft = tft;
    }

    void update(boolean isTouching, boolean *needChangeScene, int *nextSceneIndex) {
      const GameInput &input = Input::current();
      unsigned long now = millis();

      if (state == CBC_STATE_WON || state == CBC_STATE_LOST) {
        // Home ends the visit and collects the payout; a tap starts another go.
        if (input.homePressed) {
          *needChangeScene = true;
          *nextSceneIndex = gameExitSceneIndex();
        } else if (isTouching && !wasTouching) {
          resetRound(now);
        }
        wasTouching = isTouching;
        return;
      }

      if (state == CBC_STATE_READY) {
        if (now > suppressInputUntilMs && (input.homePressed || (isTouching && !wasTouching))) {
          beginPlay(now);
        }
        wasTouching = isTouching;
        return;
      }

      // Soot keep patrolling through the stumble so the board stays alive.
      updateSoot();

      if (state == CBC_STATE_HIT) {
        if (now >= hitUntilMs) {
          state = CBC_STATE_PLAYING;
          hideBanner();
        }
        wasTouching = isTouching;
        return;
      }

      updatePlayer(input, isTouching, now);
      if (playerRow >= CBC_GOAL_ROW) {
        winRound();
      } else if (playerRow > 0 && hitsSoot(playerRow - 1)) {
        onHit(now);
      }

      wasTouching = isTouching;
    }

    void render() {
      renderScene();
    }

    void initScene() {
      setBackgroundAsset(&catbus_cross_bg);

      player = meiSheet().createAvatar(0, 0, meiRunRegion(0));
      appendAvatar(player);

      SpriteSheet soot = sootSheet();
      SpriteBitmapRegion sootCell = SpriteSheet::readBitmapRegion(sprite_catbus_sootBitmaps, 0);
      for (int i = 0; i < CBC_LANE_COUNT; i++) {
        lanes[i] = soot.createAvatar(0, sootY(i), sootCell);
        // The art draws it facing the way it walks; mirror it for the lanes
        // that run the other way.
        lanes[i]->setFlipX(!movesRight(i));
        appendAvatar(lanes[i]);
      }

      SpriteSheet digits = digitSheet();
      SpriteSheetRegion zero = SpriteSheet::readRegion(sprite_digitsRegions, 0);
      for (int i = 0; i < 2; i++) {
        scoreDigits[i] = digits.createAvatar(
            CBC_SCORE_X + i * (CBC_SCORE_DIGIT_W + CBC_SCORE_GAP), CBC_SCORE_Y, zero);
        appendAvatar(scoreDigits[i]);
      }

      SpriteSheet letters = SpriteText::letterSheet();
      SpriteSheetRegion placeholder = SpriteSheet::readRegion(sprite_lettersRegions, 0);
      for (int i = 0; i < CBC_BANNER_POOL; i++) {
        bannerGlyphs[i] = letters.createAvatar(-100, -100, placeholder);
        appendAvatar(bannerGlyphs[i]);
      }

      wasTouching = false;
      suppressInputUntilMs = millis() + CBC_INTRO_GRACE_MS;
      resetRound(millis());
    }

    void destroyScene() {
      player = NULL;
      for (int i = 0; i < CBC_LANE_COUNT; i++) {
        lanes[i] = NULL;
      }
      for (int i = 0; i < 2; i++) {
        scoreDigits[i] = NULL;
      }
      for (int i = 0; i < CBC_BANNER_POOL; i++) {
        bannerGlyphs[i] = NULL;
      }
      wasTouching = false;
      GameScene::destroyScene();
    }

  private:
    Avatar *player = NULL;
    Avatar *lanes[CBC_LANE_COUNT];
    Avatar *scoreDigits[2];
    Avatar *bannerGlyphs[CBC_BANNER_POOL];

    CatBusCrossState state = CBC_STATE_READY;
    int playerRow = 0;
    int attemptsLeft = CBC_START_ATTEMPTS;
    int dodged = 0;
    int meiFrame = 0;
    unsigned long meiFrameMs = 0;
    unsigned long lastHopMs = 0;
    unsigned long suppressInputUntilMs = 0;
    unsigned long hitUntilMs = 0;
    unsigned long roundStartMs = 0;
    boolean wasTouching = false;

    SpriteSheet meiSheet() const {
      return SpriteSheet(sprite_mei, sprite_meiMask, SPRITE_MEI_WIDTH, SPRITE_MEI_HEIGHT);
    }

    SpriteSheet sootSheet() const {
      return SpriteSheet(&sprite_catbus_soot);
    }

    SpriteSheet digitSheet() const {
      return SpriteSheet(sprite_digits, sprite_digitsMask, SPRITE_DIGITS_WIDTH, SPRITE_DIGITS_HEIGHT);
    }

    SpriteSheetRegion meiRunRegion(int frame) const {
      return SpriteSheet::readRegion(sprite_meiRegions, frame % 6);
    }

    // Lanes alternate direction, bottom lane first and moving right, matching
    // the arrows in the concept art.
    bool movesRight(int lane) const {
      return (lane % 2) == 0;
    }

    float sootSpeed(int lane) const {
      float base = 1.15f + 0.22f * lane;
      return movesRight(lane) ? base : -base;
    }

    int16_t sootY(int lane) const {
      int16_t h = CBC_LANE_BOTTOM[lane] - CBC_LANE_TOP[lane] + 1;
      return CBC_LANE_TOP[lane] + (h - CBC_SOOT_H) / 2;
    }

    int16_t rowBottom(int row) const {
      if (row <= 0) {
        return CBC_START_BOTTOM;
      }
      if (row > CBC_LANE_COUNT) {
        return CBC_GOAL_Y + CBC_MEI_H;
      }
      return CBC_LANE_BOTTOM[row - 1];
    }

    // Mei is taller than a lane, so she is stood on the lane floor and simply
    // overhangs into the lane above - exactly how the concept art draws her.
    int16_t playerY(int row) const {
      return rowBottom(row) - CBC_MEI_H + 2;
    }

    float sootWrapLow() const {
      return (float)(CBC_FIELD_X0 - CBC_SOOT_MARGIN);
    }

    float sootWrapHigh() const {
      return (float)(CBC_FIELD_X1 - CBC_SOOT_W + CBC_SOOT_MARGIN);
    }

    void layoutSoot() {
      float span = sootWrapHigh() - sootWrapLow();
      for (int i = 0; i < CBC_LANE_COUNT; i++) {
        // Stagger the starting phase so the lanes never line up into a wall.
        float phase = span * ((i * 2 + 1) / (float)(CBC_LANE_COUNT * 2));
        lanes[i]->setPos(sootWrapLow() + phase, sootY(i));
        lanes[i]->requestRedraw();
      }
    }

    void updateSoot() {
      for (int i = 0; i < CBC_LANE_COUNT; i++) {
        Avatar *s = lanes[i];
        s->x += sootSpeed(i);
        if (s->x > sootWrapHigh()) {
          s->x = sootWrapLow();
        } else if (s->x < sootWrapLow()) {
          s->x = sootWrapHigh();
        }
      }
      requestRender();
    }

    bool hitsSoot(int lane) const {
      const Avatar *s = lanes[lane];
      float playerLeft = player->x + CBC_HIT_INSET;
      float playerRight = player->x + CBC_MEI_W - CBC_HIT_INSET;
      float sootLeft = s->x + CBC_HIT_INSET;
      float sootRight = s->x + CBC_SOOT_W - CBC_HIT_INSET;
      return playerLeft < sootRight && sootLeft < playerRight;
    }

    void placePlayer(int row) {
      playerRow = row;
      player->y = playerY(row);
      player->requestRedraw();
    }

    void resetPlayer() {
      player->setPos(SCREENWIDTH / 2 - CBC_MEI_W / 2, playerY(0));
      player->setVelocity(0, 0);
      player->setFlipX(false);
      playerRow = 0;
      meiFrame = 0;
      meiSheet().applyRegion(player, meiRunRegion(0));
      player->requestRedraw();
    }

    void updatePlayer(const GameInput &input, boolean isTouching, unsigned long now) {
      float vx = 0.0f;
      if (input.left) {
        vx = -CBC_PLAYER_SPEED;
      } else if (input.right) {
        vx = CBC_PLAYER_SPEED;
      }
      player->setVelocity(vx, 0);
      player->updatePos(now);

      if (player->x < CBC_FIELD_X0) {
        player->x = CBC_FIELD_X0;
      } else if (player->x + CBC_MEI_W - 1 > CBC_FIELD_X1) {
        player->x = CBC_FIELD_X1 - CBC_MEI_W + 1;
      }

      if (vx != 0.0f) {
        player->setFlipX(vx < 0);
        if ((now - meiFrameMs) >= CBC_MEI_FRAME_MS) {
          meiFrame = (meiFrame + 1) % 6;
          meiFrameMs = now;
          meiSheet().applyRegion(player, meiRunRegion(meiFrame));
        }
        requestRender();
      }

      if (wantsHop(input, isTouching, now)) {
        lastHopMs = now;
        placePlayer(playerRow + 1);
        if (playerRow <= CBC_LANE_COUNT) {
          dodged++;
          drawScore();
        }
        addSound(NOTE_G4, noteDurationMs(16, 900));
        requestRender();
      }
    }

    bool wantsHop(const GameInput &input, boolean isTouching, unsigned long now) {
      if ((now - lastHopMs) < CBC_HOP_COOLDOWN_MS) {
        return false;
      }
      if (input.homePressed) {
        return true;
      }
      if (isTouching && !wasTouching && now > suppressInputUntilMs) {
        uint16_t tx = 0;
        uint16_t ty = 0;
        if (getTouchPoint(_tft, &tx, &ty) && ty < SCREENHEIGHT / 2) {
          return true;
        }
      }
      return false;
    }

    // ---- HUD ---------------------------------------------------------------

    void drawScore() {
      int value = dodged;
      if (value > 99) {
        value = 99;
      }
      SpriteSheet sheet = digitSheet();
      int tens = value / 10;
      int ones = value % 10;
      sheet.applyRegion(scoreDigits[0], SpriteSheet::readRegion(sprite_digitsRegions, tens));
      sheet.applyRegion(scoreDigits[1], SpriteSheet::readRegion(sprite_digitsRegions, ones));
      scoreDigits[0]->requestRedraw();
      scoreDigits[1]->requestRedraw();
      requestRender();
    }

    void showBanner(const char *text) {
      SpriteSheet sheet = SpriteText::letterSheet();
      int width = SpriteText::measureWidth(text);
      int cursor = (SCREENWIDTH - width) / 2;
      int count = 0;

      for (const char *p = text; *p != '\0' && count < CBC_BANNER_POOL; ++p) {
        int index = SpriteText::letterRegionIndex(*p);
        if (index < 0) {
          cursor += SPRITE_LETTERS_CELL_W / 2;
          continue;
        }
        sheet.applyRegion(bannerGlyphs[count], SpriteSheet::readRegion(sprite_lettersRegions, index));
        bannerGlyphs[count]->setPos(cursor, CBC_BANNER_Y);
        bannerGlyphs[count]->requestRedraw();
        count++;
        cursor += SPRITE_LETTERS_CELL_W + 2;
      }

      for (int i = count; i < CBC_BANNER_POOL; i++) {
        bannerGlyphs[i]->setPos(-100, -100);
      }
      requestRender();
    }

    void hideBanner() {
      for (int i = 0; i < CBC_BANNER_POOL; i++) {
        bannerGlyphs[i]->setPos(-100, -100);
      }
      requestRender();
    }

    // ---- round flow --------------------------------------------------------

    void resetRound(unsigned long now) {
      (void)now;
      state = CBC_STATE_READY;
      attemptsLeft = CBC_START_ATTEMPTS;
      dodged = 0;
      // Full repaint first: it wipes the previous round's sprites, and the
      // redraw flags set below then bring everything back on the next render.
      drawBackgroundAsset(&catbus_cross_bg);
      layoutSoot();
      resetPlayer();
      drawScore();
      showBanner("READY");
    }

    void beginPlay(unsigned long now) {
      (void)now;
      state = CBC_STATE_PLAYING;
      roundStartMs = millis();
      hideBanner();
      addSound(NOTE_C5, noteDurationMs(8, 800));
      addSound(NOTE_E5, noteDurationMs(16, 800));
    }

    void onHit(unsigned long now) {
      attemptsLeft--;
      addSound(NOTE_A3, noteDurationMs(8, 700));
      addSound(NOTE_E3, noteDurationMs(8, 700));

      if (attemptsLeft <= 0) {
        loseRound();
        return;
      }

      state = CBC_STATE_HIT;
      hitUntilMs = now + CBC_HIT_HOLD_MS;
      resetPlayer();
      showBanner(attemptsLeft == 2 ? "OOPS" : "LAST");
    }

    // Drawn straight to the TFT under the sprite banner. Flush the pending
    // avatar moves first, otherwise the next renderScene() would repaint Mei's
    // old footprint straight through the pill. After that the board is frozen,
    // and starting another round repaints the whole background anyway.
    void showEndHint() {
      renderScene();
      uint16_t bg = rgb565(46, 32, 18);
      _tft->fillRoundRect(30, CBC_HINT_Y, SCREENWIDTH - 60, CBC_HINT_H, 6, bg);
      _tft->setTextDatum(MC_DATUM);
      _tft->setTextColor(rgb565(255, 226, 150), bg);
      _tft->drawString("Tap to replay", SCREENWIDTH / 2, CBC_HINT_Y + CBC_HINT_H / 2, 2);
      _tft->setTextDatum(TL_DATUM);
    }

    void winRound() {
      unsigned long elapsed = millis() - roundStartMs;
      if (elapsed > CBC_WIN_TIME_MS) {
        loseRound();
        return;
      }
      state = CBC_STATE_WON;
      int reward = 4 + attemptsLeft * 2;
      GameResult::report(GAME_RESULT_WIN, reward);
      mlLogGameEnd(SCENE_CAT_BUS_CROSS, GAME_RESULT_WIN, dodged, attemptsLeft,
                   (uint16_t)((millis() - roundStartMs) / 1000));
      addSound(NOTE_C5, noteDurationMs(8, 800));
      addSound(NOTE_E5, noteDurationMs(8, 800));
      addSound(NOTE_G5, noteDurationMs(8, 800));
      showBanner("GOAL!");
      showEndHint();
    }

    void loseRound() {
      state = CBC_STATE_LOST;
      GameResult::report(GAME_RESULT_LOSS, 0);
      mlLogGameEnd(SCENE_CAT_BUS_CROSS, GAME_RESULT_LOSS, dodged, 0,
                   (uint16_t)((millis() - roundStartMs) / 1000));
      addSound(NOTE_A3, noteDurationMs(4, 600));
      resetPlayer();
      showBanner("OVER");
      showEndHint();
    }
};

#endif
