#!/usr/bin/env python3
"""
Convert PNG images to Arduino RGB565 PROGMEM header files.
Compatible with TFT_eSPI pushImage and the GameBase Avatar/mask format.

Usage:
  python3 png_to_header.py art/backgrounds/washitsu_evening.png -o GameBase/BackgroundTotoroHome.h
  python3 png_to_header.py art/sprites/forest_spirit.png -o GameBase/forest_spirit.h --mask
"""

import argparse
import os
import re
from PIL import Image


def rgb_to_565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def sanitize_name(path):
    base = os.path.splitext(os.path.basename(path))[0]
    return re.sub(r"[^a-zA-Z0-9]", "_", base).upper()


def image_to_arrays(img, mask_threshold=128):
    img = img.convert("RGBA")
    w, h = img.size
    pixels = img.load()
    bitmap = []
    mask = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            bitmap.append(rgb_to_565(r, g, b))
            mask.append(1 if a >= mask_threshold else 0)
    return w, h, bitmap, mask


def format_array(values, name, values_per_line=16, dtype="uint16_t"):
    lines = [f"const {dtype} {name}[] PROGMEM={{"]
    for i in range(0, len(values), values_per_line):
        chunk = values[i : i + values_per_line]
        hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"{hex_vals},")
    lines.append("};")
    return "\n".join(lines)


def format_mask(mask, name, values_per_line=16):
    """Pack 1-bit mask into uint8_t array (8 pixels per byte, MSB first)."""
    packed = []
    for i in range(0, len(mask), 8):
        byte = 0
        for bit in range(8):
            if i + bit < len(mask) and mask[i + bit]:
                byte |= 1 << (7 - bit)
        packed.append(byte)
    return format_array(packed, name, values_per_line=16, dtype="uint8_t")


def write_header(out_path, var_prefix, w, h, bitmap, mask=None):
    guard = f"_{var_prefix}_H_"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("// Generated by tools/png_to_header.py\n\n")
        f.write(f"#define {var_prefix}_WIDTH {w}\n")
        f.write(f"#define {var_prefix}_HEIGHT {h}\n")
        f.write(format_array(bitmap, f"{var_prefix}Bitmap"))
        f.write("\n\n")
        if mask is not None:
            f.write(format_mask(mask, f"{var_prefix}Mask"))
            f.write("\n")
        f.write(f"\n#endif // {guard}\n")


def main():
    parser = argparse.ArgumentParser(description="PNG to RGB565 Arduino header")
    parser.add_argument("input", help="Input PNG path")
    parser.add_argument("-o", "--output", required=True, help="Output .h path")
    parser.add_argument("--name", help="Variable prefix (default: from filename)")
    parser.add_argument("--mask", action="store_true", help="Generate 1-bit transparency mask")
    parser.add_argument("--no-mask", action="store_true", help="Skip mask even for RGBA")
    args = parser.parse_args()

    img = Image.open(args.input)
    prefix = args.name or sanitize_name(args.input)
    w, h, bitmap, mask = image_to_arrays(img)
    use_mask = args.mask or (not args.no_mask and img.mode == "RGBA" and any(mask))
    write_header(args.output, prefix, w, h, bitmap, mask if use_mask else None)
    print(f"Wrote {args.output} ({w}x{h}, {len(bitmap)} pixels)")


if __name__ == "__main__":
    main()
